### ISSUE TITLE
Interactive `bst init` creates incorrect elements directory

### ISSUE THREAD

**Issue by sam-thursfield-nutanix** [apache/buildstream#1581]
Reproduced with Bst 1.6.3, in an empty temporary directory.

  1. Run `bst init`
  2. Specify dummy project name
  3. Press enter (default format-version)
  4. Enter non-default element path, e.g. `bst/elements`.

The `project.conf` file contains the expected element-path, however locally the directory `elements` is created and not `bst/elements`.

If path is specified on the commandline (e.g. `bst init --project-name test --element-path ./bst/elements`) then `bst/elements` *is* correctly created.

**Comment by cs-shadow** [comment]
This was actually reported and fixed a while back in https://gitlab.com/BuildStream/buildstream/-/issues/717. Although I believe it wasn't ever backported to BuildStream 1. I can confirm that it still works correctly with the latest HEAD :)

I'm not sure if this bug is severe enough to backport to BuildStream 1 at this point. As such, I'm going to close this issue for now. Although if you disagree with my assessment, certainly free to re-open.
