### ISSUE TITLE
1.6: CI failing due to Python 3.6

### ISSUE THREAD

**Issue by sam-thursfield-nutanix** [apache/buildstream#1588]
As of 11-02-2022, CI pipelines are failing for distros with Python 3.6 available:

  * Ubuntu 18.04: https://github.com/apache/buildstream/runs/5120980091?check_suite_focus=true
  * CentOS 7.7: https://github.com/apache/buildstream/runs/5120980121?check_suite_focus=true
 
The issue is: BuildStream Git tree has a single, frozen set of requirements which are used by all Python versions.

This was updated in https://github.com/apache/buildstream/pull/1564/ - which was accidentally merged despite the CI failures - breaking the branch.

The root cause is: Python 3.6 is old and some deps have dropped support already, such that there is no single frozen requirements.txt that can work with Python 3.6, 3.7, 3.8, 3.9 and 3.10 at the same time. (Proven here: https://github.com/apache/buildstream/pull/1586)

This doesn't affect *users* as `pip3 install buildstream` does not honour the frozen requirements.txt anyway. It only affects the test suite.

Also related: https://github.com/apache/buildstream/pull/1562

Options going forwards:

  * Drop Python 3.6 support - this makes sense for 'master', but we cannot do a 1.6.4. "bugfix" release that drops Py 3.6 support
  * Specify a different  frozen set of requirements for each Py version - see https://github.com/apache/buildstream/pull/1586#issuecomment-1034193819

**Comment by juergbi** [comment]
I just noticed that besides being EOL upstream, Python 3.6 is no longer supported in RHEL 7 either. Python 3.8 is supported in RHEL 7. See https://access.redhat.com/support/policy/updates/rhscl-rhel7. Python 3.8 is also available in Ubuntu 18.04 (universe repository).

With Python 3.6 effectively being unmaintained upstream and downstream and no longer supported by a growing number of Python packages, I consider it acceptable to drop official Python 3.6 support even in the 1.6.x branch. With this I don't mean that we start using Python 3.7-only constructs in the 1.6.x branch, the branch would be expected to continue working with Python 3.6. However, I'd be in favor of dropping Python 3.6 from CI, which eliminates the issue with frozen `requirements.txt`. If we accidentally break Python 3.6 support, we should still accept (reasonable) patches to fix it.

**Comment by nanonyme** [comment]
Right, that would delay the problem somewhat. We have only started noticing impossible dependencies faster because CI does exact version pinning. Things *will* break sooner or later because regardless of BuildStream various Python packages *will* start dropping Python 3.6 support quite fast this year. This was already seen once with Python 3.5.

**Comment by gtristan** [comment]
I'm a bit torn here... as I'd really like to just ditch this problem even if we're just delaying the problem.

I think that *ultimately* we should have separate frozen requirements.txt files for each supported python version, since this kind of incompatibility *can* happen and so it *will* most probably happen again one day.

> ... I consider it acceptable to drop official Python 3.6 support even in the 1.6.x branch. With this I don't mean that we start using Python 3.7-only constructs in the 1.6.x branch, the branch would be expected to continue working with Python 3.6....

This is a bit uncomfortable, if we don't test with 3.6 then it means we can accidentally let 3.7-only constructs sneak in accidentally.

With all that said, while I'd *prefer* to have 3.6 supported in the `bst-1` branch, I'm not against dropping it given it's EOL and BuildStream is also very unlikely to break with 3.6 anyway - so the fastest way forward is probably to just go ahead and drop 3.6 from CI.

I'd say overall let's just go ahead with this.

**Comment by gtristan** [comment]
This will have been fixed by #1591.
