### ISSUE TITLE
Don't add sandbox config to the cache key when BST_RUN_COMMANDS is false

### ISSUE THREAD

**Issue by abderrahim** [apache/buildstream#1687]
Changing something in the project environment (e.g. based on an option) changes the cache keys of elements, even things like stack that otherwise don't use a sandbox.

This should allow us to get rid of 089a1dce5f1d2945d302d94e287cbbd837355932 in freedesktop-sdk.

**Comment by gtristan** [comment]
The API promise is effective [since 1.95.0](https://lists.apache.org/thread/fm5sob2r93vrcgocg0k1lzz60kfoc63h), so technically we should not be allowed to make this change.

For changes which affect cache keys pre 2.0 final I feel like we could have some leniency without anyone ever noticing.

For `stack` elements there is probably no real downside to this (they cost virtually nothing to rebuild), however it may make sense if we had some way to ignore environment variables and sandbox configuration (which are two separate things) for `import` elements.

If other maintainers are also open to breaking API for cache keys in advance of 2.0 (which would also be potentially useful for #1263) perhaps we could consider some feature proposal to allow certain elements to opt-out of certain cache key contributions (maybe a private API for core elements only would be appropriate).

**Comment by gtristan** [comment]
> (maybe a private API for core elements only would be appropriate).

Not sure why I said that, it appears that `BST_RUN_COMMANDS` is already perfectly suitable for this.
