### ISSUE TITLE
buildstream goes into the background after entering a shell

### ISSUE THREAD

**Issue by abderrahim** [apache/buildstream#1690]
At the failed build prompt, answer `s` to get to a shell. When exiting the shell, bst prints the prompt again and goes to the background (or maybe is already in the background when it prints the prompt), and I need to run `fg` to get back to it.

**Comment by nanonyme** [comment]
I have also sen variation of this where BuildStream is not in background until after you exit the shell.

**Comment by gtristan** [comment]
> I have also sen variation of this where BuildStream is not in background until after you exit the shell.

I have only seen this variation (recently), years ago I saw the other.

This is tricky to get right and may depend on the shell implementation in the sandbox IIRC

**Comment by abderrahim** [comment]
I'm not sure what you mean by "BuildStream is not in background until after you exit the shell" as I don't see what's the difference with what I said.

**Comment by nanonyme** [comment]
I must have misread the issue. Yes, this is ongoing

**Comment by adoakley** [comment]
What's happening here is that the shell ends up in it's own process group, and calls `tcsetpgrp` in order to make it the terminal foreground process group.  When the shell exits nothing makes buildbox the foreground process group again (shells typically have code to do this, but it can't work inside the pid namespace).  Buildbox attempts to read from the terminal while it's not the foreground process group and gets a `SIGTTIN` from the kernel.  This signal stops the process.

This issue was previously fixed by change 8f401127c450ea1c2a1e2878d2ac28a7166d355c, but that code has been removed in favor of buildbox-run.

The code to fix this seems fairly simple, but I'm not sure where the best place for it is - buildstream, buildbox, or bubblewrap.
