### ISSUE TITLE
remove `index` and `storage` artifact/source cache type

### ISSUE THREAD

**Issue by abderrahim** [apache/buildstream#1693]
Once upon a time, we had a non-standard API for storing artifact information. However, we now use the remote asset API which is part of the remote execution APIs. We no longer need to have separate index and storage for the cache.

Even for implementations that separate the CAS and remote asset, we can just push the responsibility to whoever is deploying it to just add a traefik proxy.

**Comment by gtristan** [comment]
Right now the client has the ability to deal with setups where the `AssetCache` is separate from the `CAS`, which I think is nice to keep.

Also our API is stable since our last beta, so we can't rightly remove this.

That said, it can be an interesting feature to add which allows the client to communicate with the same URI configuration for both indexing and storage.

But there is one really big problem with adding such a new feature... looking at the code right now, it appears that the feature is already supported :-/

It is called the `all` type: https://docs.buildstream.build/master/using_config.html#cache-servers ... and in fact it is the default, so if you specify a cache server and neglect to specify the `type`, it is assumed to be usable for both indexing and storage.

**Comment by abderrahim** [comment]
Indeed, this is not about adding a feature but rather about removing one. I don't think it is useful, and it would be nice to not have to support it. For instance, it is the main reason we still have bst-artifact-server for the tests.

Either way, this needs to be discussed with the other developers and would be either a blocker or a "won't fix".

**Comment by gtristan** [comment]
It’s a clear API break, afaics that ship has sailed.

Even if we were still an unstable API, I very much disagree with the statement *"we can just push the responsibility to whoever is deploying it to just add a traefik proxy."*

Setting up a traefik proxy is a nasty bit of business that can take hours or even a whole day to figure out, which is why I ended up putting up this traefik hack example: https://gitlab.com/BuildStream/buildbarn4bst1 - I wouldn't want to impose that on users either.

**Comment by gtristan** [comment]
Let's close this as it is an API break and there does not seem to be an urgent reason to do this.
