### ISSUE TITLE
Error out in situations where conditional statements `(?)` can never evaluate `true`

### ISSUE THREAD

**Issue by nanonyme** [apache/buildstream#1798]
We noticed after removal of conf-extra that variable resolution is incorrect and has probably been all the time with conf-extra papering over the bug. We have element definition here https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/blob/master/elements/bootstrap/build/gcc-stage1.bst#L68 that uses conf-extra, however, we are setting it for all target option possibilities in https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/blob/master/elements/bootstrap/include/gcc-arch-opts.yml.

It looks like with conf-extra in plugin configuration as empty string final values were correct (although resolution was incorrect) but now that conf-extra is removed, bst2 simply fails with this construct.

**Comment by gtristan** [comment]
Interesting - this is an fdsdk bug, and on the buildstream side, it is unfortunate that there is no obvious way to report a better error.

The issue is that by default on an `x86_64` machine, the arch will resolve to `x86_64` (regardless of how your host reports it, it will be normalized to a machine name supported by REAPI).

Looking at https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/blob/master/elements/bootstrap/include/gcc-arch-opts.yml, there is no default specified for `conf-extra`, so effectively fdsdk is not defining any `conf-extra` variable for the `x86_64` target_arch.

Interestingly, fdsdk *does* check if the `target_arch` is equal to the string `"x86-64"` and provides some values, but there is no architecture named `x86-64` so that does not happen.

While BuildStream does have good control on how options are *specified* and will give you a good error, say in this case:
```
tristan@pony:~/work/freedesktop-sdk$ bst -o target_arch x86-64 show bootstrap/build/gcc-stage1.bst 

Error loading project: Invalid value for arch option 'target_arch': x86-64
Valid values: arm, aarch64, i686, x86_64, ppc64le, ppc64, riscv64
```
BuildStream does *not* have similar support to how conditional statements compare project options to impossible values. It would certainly be desirable to have such an error, but this is tricky to do as the conditional statements are just python-like generic statements processed by Jinja2.

I will retitle and rebrand this issue accordingly, while preserving the initial description in order to highlight a use case where this can easily bite users.

**Comment by nanonyme** [comment]
This is even more confusing because it happened on aarch64 which clearly is not building x86_64 cross-compiler.

**Comment by nanonyme** [comment]
@gtristan your assessment seemed to be not complete. https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/jobs/3435905448 remains failing after the suggested change

**Comment by nanonyme** [comment]
I will rewrite the description and title back. The original issue is fixed and bug persists.

**Comment by nanonyme** [comment]
Oh, this is actually same case. The condition is missing!

**Comment by nanonyme** [comment]
This is IMHO not a BuildStream bug in the end. It is expected behaviour that BuildStream does not error if conditionals do not match. There is no if-elif-else construct available. It turns out there are two bugs here in freedesktop-sdk: one was the x86-64 vs x86_64 and the other is that aarch64 was missing completely. I will fix both.

**Comment by nanonyme** [comment]
The second bug was aarch64 definition was missing completely. After fixing both these bugs there is now clear error that this variable is not defined on unsupported arches.

**Comment by gtristan** [comment]
> This is IMHO not a BuildStream bug in the end. It is expected behaviour that BuildStream does not error if conditionals do not match. There is no if-elif-else construct available. It turns out there are two bugs here in freedesktop-sdk: one was the x86-64 vs x86_64 and the other is that aarch64 was missing completely. I will fix both.

Right, there is nothing we could do about unhandled `aarch64`, however we *do* know that an enum project option (or an arch option) can only have specific values, and we *could* potentially detect a situation where you are checking an expression which could never be true.

IMO this could have saved some time with an early error.
