### ISSUE TITLE
CI image testing completely broken

### ISSUE THREAD

**Issue by nanonyme** [apache/buildstream#1801]
Filing here as this blocks BuildStream project as it consumes images from https://gitlab.com/BuildStream/buildstream-docker-images/-/pipelines. This should be bst2 blocker. It's not possible to test any buildbox updates anymore as image builds are broken

**Comment by cs-shadow** [comment]
should be fixed by https://gitlab.com/BuildStream/buildstream-docker-images/-/merge_requests/210

new images have since been published from this pipeine - https://gitlab.com/BuildStream/buildstream-docker-images/-/pipelines/734361636

There seems to be some issues with the combination of grpcio 1.46, python3.11 and buildstream testsuite. But I think it's fair to say that it's a different issue than this, so resolving this.
