### ISSUE TITLE
bst2: Tracking is broken

### ISSUE THREAD

**Issue by AdrianVovk** [apache/buildstream#1851]
Trying to port carbonOS to bst2 (specifically, 2.0.1). Using `project.refs`. Running in a `fedora:38` distrobox container, w/ buildstream `pip install`'d into /usr/local

Some packages I track will error out with bugs like this:

```
[00:00:25][????????][   track:pkgs/fonts/twemoji.bst        ] BUG     Track

    An unhandled exception occured:
    
    Traceback (most recent call last):
      File "/usr/local/lib64/python3.11/site-packages/buildstream/_projectrefs.py", line 144, in _lookup
        node = element_list.mapping_at(source_index)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "src/buildstream/node.pyx", line 1262, in buildstream.node.SequenceNode.mapping_at
      File "src/buildstream/node.pyx", line 1278, in buildstream.node.SequenceNode.mapping_at
    IndexError: list index out of range
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/usr/local/lib64/python3.11/site-packages/buildstream/_scheduler/jobs/job.py", line 438, in child_action
        result = self.child_process()  # pylint: disable=assignment-from-no-return
                 ^^^^^^^^^^^^^^^^^^^^
      File "/usr/local/lib64/python3.11/site-packages/buildstream/_scheduler/jobs/elementjob.py", line 91, in child_process
        return self._action_cb(self._element)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/local/lib64/python3.11/site-packages/buildstream/_scheduler/queues/trackqueue.py", line 65, in _track_element
        return element._track()
               ^^^^^^^^^^^^^^^^
      File "/usr/local/lib64/python3.11/site-packages/buildstream/element.py", line 1390, in _track
        return self.__sources.track(self._get_workspace())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/local/lib64/python3.11/site-packages/buildstream/_elementsources.py", line 97, in track
        new_ref = source._track()
                  ^^^^^^^^^^^^^^^
      File "/usr/local/lib64/python3.11/site-packages/buildstream/source.py", line 1214, in _track
        self._set_ref(new_ref, save=False)
      File "/usr/local/lib64/python3.11/site-packages/buildstream/source.py", line 1065, in _set_ref
        node = toplevel_refs.lookup_ref(project.name, element_name, element_idx, write=True)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/local/lib64/python3.11/site-packages/buildstream/_projectrefs.py", line 113, in lookup_ref
        node = self._lookup(self._toplevel_save, project, element, source_index, ensure=True)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/local/lib64/python3.11/site-packages/buildstream/_projectrefs.py", line 150, in _lookup
        node = element_list.mapping_at(source_index)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "src/buildstream/node.pyx", line 1262, in buildstream.node.SequenceNode.mapping_at
      File "src/buildstream/node.pyx", line 1278, in buildstream.node.SequenceNode.mapping_at
    IndexError: list index out of range
```

Tracking this element:

```
# Check for updates here: https://koji.fedoraproject.org/koji/packageinfo?packageID=26306
sources:
- kind: remote
  url: https://kojipkgs.fedoraproject.org//packages/twitter-twemoji-fonts/14.0.2/3.fc38/noarch/twitter-twemoji-fonts-14.0.2-3.fc38.noarch.rpm
  filename: twemoji.rpm
- kind: local
  path: files/fontconfig/75-twemoji.conf
# manual-updates

# For extracting the RPM
- kind: git
  url: github:rpm-software-management/rpm
  directory: rpm
```

This bug is oddly inconsistent. I can reliably reproduce it by deleting `project.refs`. Then it'll fail to track (same packages every time). After it fails, I type `r` to make buildstream retry. Then it "succeeds", but incorrectly tracks the `kind: remote` source. So I re-track the package, and it tracks everything correctly. See the log

```
$ rm project.refs
$ bst source track pkgs/fonts/twemoji.bst
... (error from above) ...
Track failure on element: pkgs/fonts/twemoji.bst
...
Choice: [continue]: r
Retrying failed job
[--:--:--][????????][   track:pkgs/fonts/twemoji.bst        ] START   carbonOS/pkgs-fonts-twemoji/????????-track.2231251.log
[--:--:--][????????][   track:pkgs/fonts/twemoji.bst        ] START   Tracking https://kojipkgs.fedoraproject.org//packages/twitter-twemoji-fonts/14.0.2/3.fc38/noarch/twitter-twemoji-fonts-14.0.2-3.fc38.noarch.rpm
[00:00:00][????????][   track:pkgs/fonts/twemoji.bst        ] SUCCESS Tracking https://kojipkgs.fedoraproject.org//packages/twitter-twemoji-fonts/14.0.2/3.fc38/noarch/twitter-twemoji-fonts-14.0.2-3.fc38.noarch.rpm
[--:--:--][????????][   track:pkgs/fonts/twemoji.bst        ] START   Tracking master from https://github.com/rpm-software-management/rpm
[00:00:00][????????][   track:pkgs/fonts/twemoji.bst        ] SUCCESS Tracking master from https://github.com/rpm-software-management/rpm
[--:--:--][????????][   track:pkgs/fonts/twemoji.bst        ] INFO    Found new revision: ('2043f2ac57ae2690cc1b11242f040085df8eed83', [])
[00:00:01][????????][   track:pkgs/fonts/twemoji.bst        ] SUCCESS carbonOS/pkgs-fonts-twemoji/????????-track.2231251.log
[00:00:02][        ][    main:core activity                 ] SUCCESS Track
...
$ cat project.refs
projects:
  carbonOS:
    pkgs/fonts/twemoji.bst:
    - {}
    - {}
    - ref: 2043f2ac57ae2690cc1b11242f040085df8eed83
$ bst source track pkgs/fonts/twemoji.bst
...
[--:--:--][????????][   track:pkgs/fonts/twemoji.bst        ] START   carbonOS/pkgs-fonts-twemoji/????????-track.2231963.log
[--:--:--][????????][   track:pkgs/fonts/twemoji.bst        ] START   Tracking https://kojipkgs.fedoraproject.org//packages/twitter-twemoji-fonts/14.0.2/3.fc38/noarch/twitter-twemoji-fonts-14.0.2-3.fc38.noarch.rpm
[00:00:00][????????][   track:pkgs/fonts/twemoji.bst        ] SUCCESS Tracking https://kojipkgs.fedoraproject.org//packages/twitter-twemoji-fonts/14.0.2/3.fc38/noarch/twitter-twemoji-fonts-14.0.2-3.fc38.noarch.rpm
[--:--:--][????????][   track:pkgs/fonts/twemoji.bst        ] INFO    Found new revision: a842447e8610bce8a0564a91604a2988220285b5f60b0396440ead230ac6b1ec
[--:--:--][????????][   track:pkgs/fonts/twemoji.bst        ] START   Staging local files into CAS
[00:00:00][????????][   track:pkgs/fonts/twemoji.bst        ] SUCCESS Staging local files into CAS
[--:--:--][????????][   track:pkgs/fonts/twemoji.bst        ] START   Tracking master from https://github.com/rpm-software-management/rpm
[00:00:01][????????][   track:pkgs/fonts/twemoji.bst        ] SUCCESS Tracking master from https://github.com/rpm-software-management/rpm
[00:00:02][????????][   track:pkgs/fonts/twemoji.bst        ] SUCCESS carbonOS/pkgs-fonts-twemoji/????????-track.2231963.log
[00:00:02][        ][    main:core activity                 ] SUCCESS Track
...
$ cat project.refs
projects:
  carbonOS:
    pkgs/fonts/twemoji.bst:
    - ref: a842447e8610bce8a0564a91604a2988220285b5f60b0396440ead230ac6b1ec
    - {}
    - ref: 2043f2ac57ae2690cc1b11242f040085df8eed83
```

This issue is not exclusive to this one element. it also happens w/ others:

```
sources:
- kind: git_tag
  url: github:systemd/zram-generator
  track: main
  exclude:
  - v*-rc*
  - v*-beta*
- kind: gen-cargo-lock
- kind: cargo
```

```
sources:
- kind: git_tag
  url: github:cpuguy83/go-md2man
- kind: patch
  path: patches/md2man/fix-go-ver.patch
- kind: go-vendor
```

```
sources:
- kind: tar
  url: https://static.crates.io/crates/gst-plugin-dav1d/gst-plugin-dav1d-0.10.0.crate
- kind: gen-cargo-lock
- kind: cargo
```

The `gen-cargo-lock` and `go-vendor` plugins are custom to carbonOS. [Sources here](https://gitlab.com/carbonOS/build-meta/-/tree/35f91b6d/plugins). I am not suspecting them, however, since another element that uses none of them exhibits the same issue.

**Comment by AdrianVovk** [comment]
While collecting info for #1852, I was able to reproduce this issue for `pkgs/fonts/twemoji.bst` in a `docker.io/buildstream/buildstream:dev` toolbox container. All the other elements that exhibited this bug here, exhibited #1852 in that container instead

**Comment by AdrianVovk** [comment]
OK I think I've figured this one out. Here's a minimal reproducer:

```yaml
sources:
- kind: local
  path: project.conf
- kind: remote
  url: https://bing.com
```

The crash happens when any non-trackable element (i.e. `kind: local`) precedes an element that actually implements tracking. The problem is here: https://github.com/apache/buildstream/blob/master/src/buildstream/_projectrefs.py#L149.

If `project.refs` is empty, then we append a blank dict to the list and then get the specified index. However, a `kind: local` element never reaches this code path. Thus, we end up with one less empty dictionary than expected!

In the above example:

```
element_list = []

# Here, we start processing the kind:local source
(nothing happens, since there's nothing to track)

# Here, we start processing the kind:remote source
element_list.mapping_at(1) -> raises IndexError
element_list.append({}) -> element_list is now [{}]
element_list.mapping_at(1) -> STILL AN INDEX ERROR! We were expecting element_list = [{}, {}]
```

Not sure how to fix

**Comment by gtristan** [comment]
Ok so at a glance, I can see some pretty bad problems with your plugins... looking right now at https://gitlab.com/carbonOS/build-meta/-/blob/35f91b6d/plugins/gen-cargo-lock.py

Your source does not properly implement `load_ref()`, `get_ref()`, `set_ref()`, `get_unique_key()`, `is_cached()` or `is_resolved()`. I hope that you have tried to read through https://docs.buildstream.build/2.0/buildstream.source.html as this should help, but I think a fundamental understanding needs to be explained somewhere in the documentation to make plugin authoring more intuitive, I'm not sure where in the docs or how best to explain this.

### Overall reproducibility expectations

At a high level, I should say that it is important that your source plugin expects to be able to work without ever running `bst source track`, this means that either at `bst source fetch` time, the `ref` should be pointing at data which is possible to download from the internet reliably (such that the downloaded data is guaranteed to be bit-for-bit identical every time it is downloaded, like a git commit or a file checksum) **or** in a case like the one you are trying to implement, where this is simply not possible, then the data itself should be stored in the source *ref*.

After a build pipeline has been *tracked* successfully, then it is considered *resolved* (the plugin can indicate this by returning `True` from `is_resolved()`)... in other words... the entire pipeline's cache keys have been *resolved* and we know *exactly* what the inputs are going to be for the build, at least as far as the source inputs go, they are now guaranteed to be bit-for-bit identical for a given project's resolved cache keys.

At this time, it is expected that your project (possibly including your project.refs) represents something which can be *reproduced* (whether the output will be bit-for-bit identical depends on other factors, but the overall build is considered *repeatable* at least).

In other words, *even* if you did not choose to revision your `project.refs` file in git, I should be able to clone your repository, and with the `project.refs` file which you emailed me out of band (or a `project.refs` file which I downloaded from a CI artifact or obtained as a part of an official release), I should be able to reproduce your build exactly on my own infra.

### Specific reasons why your plugin wont work

Here are some reasons I can see that your plugin cannot possibly work and why

* The data obtained in `bst source track` by way of running `cargo generate-lockfile` is not available to me when I build. It is instead stored in the local source cache `~/.cache/buildstream/sources/gen-cargo-lock/Cargo.lock` on the remote machine where you ran `bst source track`, as such it is only available on that build host where you ran `bst source track` - dirty, but might work in a very limited sense.
  * As a side note, **_every_ source which uses `gen-cargo-lock` in your project shares the _same_ `Cargo.lock` file**, because you have put it directly at the root of the mirror directory owned by the `gen-cargo-lock` source *kind*.
  * We should ignore this for now, because I don't think you can implement this plugin by using the local filesystem source cache directories
* The state of the lock file is not accounted for in the source unique key
  * This means that your plugin's contribution to the cache key is the same value regardless of the state of the `Cargo.lock`
  * Consequently, your plugin risks introducing different data for the same cache key, risking the following scenario:
    * You first successfully build an artifact for that *cache key*
    * You now run `bst source track`, on that element, obtaining *new* dependencies in your `Cargo.lock`
    * You now run `bst build` for that element, but the element is already cached under the *same* cache key, and no build is run
  * As a general rule, usually at least the *ref* is included as a part of the value returned by `get_unique_key()`.

### General recommendation

Your edge case plugin has the property that the *tracked* data (usually intended to be a *reference* for something to download or *"fetch"*) cannot be stored separately from the project data, and cannot be *fetched*.

In order to implement this reliably, I would recommend that you store the results of `cargo generate-lockfile` directly in the *ref*.

As such, functionality would run like this:

* `bst source track`

  At track time, after running `cargo generate-lockfile`, you read the generated lockfile and serialize it as a string to be stored as the *ref*, properly *returning* that string from your `Source.track()` implementation.

  You *must* then also implement `Source.set_ref()`, `Source.get_ref()` and `Source.load_ref()`, simply by treating the ref as a string, and just name it as `ref` for the purpose of implementing these; this will result in storing the *contents* of the discovered `Cargo.lock` file as a serialized string in the `project.refs` file.

* `bst source fetch`

  At fetch time, your plugin does nothing.

* `Source.get_unique_key()`

  Simply include the ref in the data returned by this function, ensuring that your source plugin reports a key that is unique for the data which it intends to introduce into the build.

* `Source.stage()`

  Here we want to take the serialized `ref`, deserialize it and write the `Cargo.lock` file in the desired location.

* `Source.is_resolved()`

  Returns `True` if the `self.ref is not None`

* `Source.is_cached()`

  Simply returns `self.is_resolved()`

This approach should be fairly simple to implement and should work properly in all bst use cases.

**Comment by AdrianVovk** [comment]
> Ok so at a glance, I can see some pretty bad problems with your plugins... looking right now at https://gitlab.com/carbonOS/build-meta/-/blob/35f91b6d/plugins/gen-cargo-lock.py

I'm sorry, but you looked at the wrong plugin!! `gen-cargo-lock` is a very special case, as I'll explain below. My other plugins (`gnu` and `go-vendor`) should be a lot more normally implemented

Also, I didn't write this one! I got it from here: https://gitlab.com/BuildStream/bst-plugins-experimental/-/merge_requests/223

This is part of my bst2 port. The bst1 version of the `gen-cargo-lock` plugin that I wrote _did_ actually store `Cargo.lock` in `project.refs` for exactly the reasons you detail. However, when trying to figure out how to port my plugins to `bst2`, I came across the existing plugin I linked above and realized that's a much cleaner solution.

> Your source does not properly implement load_ref(), get_ref(), set_ref(), get_unique_key(), is_cached() or is_resolved()

This is because it doesn't need to. `gen-cargo-lock` is a source that is always immediately followed by a `cargo` source. The `Cargo.lock` file this plugin generates is used for exactly one purpose: by the `cargo` source while tracking. All the data contained in the `Cargo.lock` file gets turned into buildstream refs by the `cargo` source and put into `project.refs`, so there's no need for the `gen-cargo-lock` plugin to have a unique ID. At build time, `cargo` has all of its dependencies vendored and so it doesn't need to look at `Cargo.lock`. See [here in my `project.refs`](https://gitlab.com/carbonOS/build-meta/-/blob/6f57dc2e/project.refs#L732-1020) for an example of this

Here's the various steps:
- During tracking, the `cargo` plugin needs a `Cargo.lock` file. Some projects don't ship one. So, we stage a `gen-cargo-lock` element to generate it. Then the `cargo` plugin executes, reads the `Cargo.lock` file we just generated, and turns it into buildstream refs for all the dependencies. The unique-id is calculated from the ref the `cargo` plugin generated, which will be the real source of truth when it comes time to stage the sources for the build
- During fetch, we already have all the version numbers and hashes of all dependencies tracked under the `cargo` plugin's ref. So, we download those dependencies. This is done by the `cargo` source. `Cargo.lock` is redundant here
- During stage, it's the same as fetch. We have all the data available, so we set up a special vendoring directory and populate it with all the libraries. Again, all done by the `cargo` source. `Cargo.lock` is redundant here

If it doesn't work for some reason (i.e. if the toolchain in the sandbox really does need `Cargo.lock` around during the build) I'll serialize the file into a ref like I did before and like you describe.

> but I think a fundamental understanding needs to be explained somewhere in the documentation to make plugin authoring more intuitive, I'm not sure where in the docs or how best to explain this.

I absolutely agree. `bst`'s plugin architecture definitely felt confusing/overwhelming when I first started writing plugins. And I made lots of the mistakes you detail here. I fixed them over time as people tried to build my project in their own clean environment and failed, and that taught me how the system works. But it'd be nice if it could be documented enough to get it right the first time :)

A lot of what you wrote here, especially the "Overall reproducibility expectations" section, would be useful in the docs. Otherwise the plugin architecture feels a bit impenetrable. Some extra docs regarding URL translation (when should it be done? how? what does it mean to mark a URL? why does this need to be done?) would be nice too; that stuff still confuses me...

It can probably just be top-level documentation for the `Source` class itself (i.e. [here](https://docs.buildstream.build/2.0/buildstream.source.html)). Worst-case, you can add to the Additional Writings section

> As a side note, every source which uses gen-cargo-lock in your project shares the same Cargo.lock file, because you have put it directly at the root of the mirror directory owned by the gen-cargo-lock source kind.

Hmm so this might be a problem if multiple tracks are happening in parallel. Again, we only need to ferry the data from one source to the very next source, and then that one will turn it into an actual ref. My concern here is that if we have multiple cargo projects being tracked in parallel, they share the one file and trample each-other. Somes like I just need to incorporate the project and element name into the local cache name to avoid a race condition

> Consequently, your plugin risks introducing different data for the same cache key, risking the following scenario: 

This might be an issue if the build chain ends up looking at the `Cargo.lock` file anyway, despite not having a need to since all dependencies are already vendored.

It would be nice if I could tell, from `stage`, if I'm staging for a track or for a build. If it's for a track I'd stage `Cargo.lock`, but if it's for a build I'd stage nothing to ensure consistency between builds

**Comment by gtristan** [comment]
Hi,

> > Ok so at a glance, I can see some pretty bad problems with your plugins... looking right now at https://gitlab.com/carbonOS/build-meta/-/blob/35f91b6d/plugins/gen-cargo-lock.py
> 
> I'm sorry, but you looked at the wrong plugin!! `gen-cargo-lock` is a very special case, as I'll explain below. My other plugins (`gnu` and `go-vendor`) should be a lot more normally implemented
> 
> Also, I didn't write this one! I got it from here: https://gitlab.com/BuildStream/bst-plugins-experimental/-/merge_requests/223

Just trying to be helpful, I think that once you have an understanding of the generally simple architecture, plugin writing becomes fairly intuitive - but I think our docs don't do a great job for new users to get into the flow.


> > Your source does not properly implement load_ref(), get_ref(), set_ref(), get_unique_key(), is_cached() or is_resolved()
>
> This is because it doesn't need to. `gen-cargo-lock` is a source that is always immediately followed by a `cargo` source. The `Cargo.lock` file this plugin generates is used for exactly one purpose: by the `cargo` source while tracking. All the data contained in the `Cargo.lock` file gets turned into buildstream refs by the `cargo` source and put into `project.refs`, so there's no need for the `gen-cargo-lock` plugin to have a unique ID. At build time, `cargo` has all of its dependencies vendored and so it doesn't need to look at `Cargo.lock`. See [here in my `project.refs`](https://gitlab.com/carbonOS/build-meta/-/blob/6f57dc2e/project.refs#L732-1020) for an example of this

Yeah, reading this I'm not really confident that this is going to work well.

I understand your general logic but I do think this plugin steps out of bounds and will fall into scenarios that will break.

There is *definitely* the issue of race conditions around the local caching of the `Cargo.lock` file in `Source.get_mirror_directory()` even if the intention is to treat this as a transiently needed file which is later ignored, parallel tracking of `gen-cargo-lock` sources in different elements will have them all writing to the same file.

I'm not sure if the `cargo` plugin will generate the `Cargo.lock` file in the build directory which will likely be relevant at build time, and we could also be intentionally *overwriting* an existing `Cargo.lock` file in the external rust source tree that differs from the one we tracked.

Finally, the `gen-cargo-lock` *is* responsible for staging the `Cargo.lock`, and in this setup the `Cargo.lock` will *only* exist on a machine where tracking previously occurred.

Also I should point out that with BuildStream 2, the results of `Source.stage()` are cached in the CAS, which means that the unique key of the `gen-cargo-lock` source *by itself* is significant - subsequent runs of `bst source track` + `bst build` will likely end up re-staging an old staging result from previous runs due to the source cache key being unchanged and available in the CAS.

I don't think there is any safe way to do this without either:

* Serializing the `Cargo.lock` as you mentioned you had previously done, that sounds like the sanest approach
* There is another alternative I considered for the sake of *"prettiness"* which is for example, if you have some additional infra
  * At `Source.track()` time, the resulting Cargo.lock could be uploaded to an artifactory instance as a file named after the `Cargo.lock` sha256sum
  * The sha256sum could be used as a ref
  * `Source.fetch()` would download the lock from artifactory

This second approach is also totally viable, but I didn't want to suggest it because it involves additional infra / moving parts, so while it may be more *"pretty"* to look at the resulting bst files, it's not a win.

[...]
> > but I think a fundamental understanding needs to be explained somewhere in the documentation to make plugin authoring more intuitive, I'm not sure where in the docs or how best to explain this.
> 
> I absolutely agree. `bst`'s plugin architecture definitely felt confusing/overwhelming when I first started writing plugins. And I made lots of the mistakes you detail here. I fixed them over time as people tried to build my project in their own clean environment and failed, and that taught me how the system works. But it'd be nice if it could be documented enough to get it right the first time :)
> 
> A lot of what you wrote here, especially the "Overall reproducibility expectations" section, would be useful in the docs. Otherwise the plugin architecture feels a bit impenetrable. Some extra docs regarding URL translation (when should it be done? how? what does it mean to mark a URL? why does this need to be done?) would be nice too; that stuff still confuses me...
> 
> It can probably just be top-level documentation for the `Source` class itself (i.e. [here](https://docs.buildstream.build/2.0/buildstream.source.html)). Worst-case, you can add to the Additional Writings section

Yeah I'm not sure where to put this kind of thing, I think probably we need a solid *"Introduction"* which should be required reading for any of the plugin authoring documentation (elements & sources alike), which should help the further reading be more intuitive.

On a side note, I am really happy to hear that you have been leveraging the plugin system successfully :)

> > As a side note, every source which uses gen-cargo-lock in your project shares the same Cargo.lock file, because you have put it directly at the root of the mirror directory owned by the gen-cargo-lock source kind.
> 
> Hmm so this might be a problem if multiple tracks are happening in parallel. Again, we only need to ferry the data from one source to the very next source, and then that one will turn it into an actual ref. My concern here is that if we have multiple cargo projects being tracked in parallel, they share the one file and trample each-other. Somes like I just need to incorporate the project and element name into the local cache name to avoid a race condition

Right, I pre-followed up on just that above, sorry but I have to just scan through and reply ;-)

Again, I don't think this approach is really viable.

> > Consequently, your plugin risks introducing different data for the same cache key, risking the following scenario:
> 
> This might be an issue if the build chain ends up looking at the `Cargo.lock` file anyway, despite not having a need to since all dependencies are already vendored.
> 
> It would be nice if I could tell, from `stage`, if I'm staging for a track or for a build. If it's for a track I'd stage `Cargo.lock`, but if it's for a build I'd stage nothing to ensure consistency between builds

Generally speaking, we don't want to give plugin methods more context than what is strictly necessary, as plugin methods are things we can later decide to call in different ways when refactoring the core and making core improvements - it is best to keep the APIs simple and strict.

That said, there is no such context; sources are staged when the core asks the source to stage the data, when the *core* decides, this happens only if the `Source.is_cached()` condition is satisfied.

I should point out that the `gen-cargo-lock` lies about `Source.is_cached()` and `Source.is_resolved()` because it pretends to be cached, and pretends to know what data will be cached respectively, when it in fact does not (i.e. when you call `bst build` *without* previously having called `bst source track`, it is inevitably busted).

**Comment by AdrianVovk** [comment]
You bring up fair points.

I think the best approach would be for the cargo plugin itself to generate a Cargo.lock file if one is missing, then parse it into a ref, then throw out the result. That way, we don't store redundant data in the ref, and we don't have such a weird and probably broken plugin.

**Comment by gtristan** [comment]
Ah sorry I missed this comment... and commented instead at https://github.com/apache/buildstream-plugins/issues/44#issuecomment-1672495298
